# Generated by Django 2.2.24 on 2021-11-05 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tg_id', models.IntegerField(blank=True, null=True)),
                ('tg_username', models.TextField(blank=True, null=True)),
                ('first_name', models.TextField(blank=True, null=True)),
                ('patronymic', models.FloatField(blank=True, null=True)),
                ('last_name', models.TextField(blank=True, null=True)),
                ('country', models.TextField(blank=True, null=True)),
                ('region', models.TextField(blank=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('date_birthday', models.TextField(blank=True, null=True)),
                ('document_type', models.TextField(blank=True, null=True)),
                ('credit_card', models.IntegerField(blank=True, null=True)),
                ('balance', models.IntegerField(blank=True, null=True)),
                ('type_payment', models.IntegerField(blank=True, null=True)),
                ('status', models.TextField(default='Не принят')),
            ],
            options={
                'db_table': 'accounts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Completed',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=50)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Accounts')),
                ('registrator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
