# Generated by Django 3.2.9 on 2021-11-05 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_mailing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completed',
            name='status',
        ),
    ]
