# Generated by Django 3.2.9 on 2021-11-05 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_completed_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='completed',
            name='status',
            field=models.CharField(default='Не принят', max_length=50),
        ),
    ]
