# Generated by Django 3.2.9 on 2021-11-05 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_completed_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completed',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
