# Generated by Django 3.2.9 on 2021-11-09 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_completed_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='completed',
            name='instruction',
            field=models.TextField(default='none'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='completed',
            name='link',
            field=models.CharField(default='none', max_length=50),
            preserve_default=False,
        ),
    ]
