# Generated by Django 3.2.9 on 2021-11-10 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_passportfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='passportfile',
            name='account_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.accounts'),
            preserve_default=False,
        ),
    ]
