# Generated by Django 3.2.9 on 2021-11-10 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_passportfile_account_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passportfile',
            name='account_id',
        ),
    ]
