# Generated by Django 3.2.9 on 2021-11-23 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0009_remove_passportfile_account_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferalAccount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tg_id', models.IntegerField()),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('balance', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='mailing',
            name='create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='MultiAccounts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tg_id', models.IntegerField()),
                ('first_last_field', models.BooleanField(default=False)),
                ('credit_card_field', models.BooleanField(default=False)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.accounts')),
            ],
        ),
        migrations.CreateModel(
            name='BanList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tg_id', models.IntegerField()),
                ('reason', models.CharField(max_length=255)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.accounts')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
