# Generated by Django 3.2.9 on 2021-11-24 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20211123_0930'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReferalAccount',
        ),
    ]
