# Generated by Django 3.2.9 on 2021-11-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_delete_referalaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='tg_username',
            field=models.CharField(max_length=255),
        ),
    ]
