# Generated by Django 3.2.9 on 2022-02-24 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_accounts_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='new_status',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='patronymic',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='status',
            field=models.TextField(default=None),
        ),
    ]
