# Generated by Django 3.2.9 on 2022-02-24 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20220224_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='worker',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
