# Generated by Django 3.2.9 on 2022-02-24 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_accounts_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='new_status',
            field=models.TextField(blank=True, db_index=True, default='Входящая'),
        ),
    ]
