# Generated by Django 3.2.9 on 2022-02-25 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_accounts_new_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
