# Generated by Django 3.2.9 on 2022-03-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_accounts_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='chat_link',
            field=models.TextField(null=True),
        ),
    ]
