# Generated by Django 3.2.9 on 2021-11-03 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Referals',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('from_id', models.IntegerField(blank=True, null=True)),
                ('to_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'referals',
                'managed': False,
            },
        ),
    ]
