# Generated by Django 3.2.9 on 2022-03-05 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referals',
            options={},
        ),
    ]
