# Generated by Django 3.2.9 on 2022-03-05 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referals', '0002_alter_referals_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='referals',
            name='type_payment',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
