# Generated by Django 3.2.9 on 2022-03-05 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referals', '0003_referals_type_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='referals',
            name='status',
            field=models.TextField(blank=True, null=True),
        ),
    ]
